name: Docker Image CI

run-name: Docker Image CI for ${{ github.event.inputs.docker_image }} image. Run ${{ github.run_number }}

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: 'Docker image name'
        required: true
        type: choice
        options:
          - 'missaelcorm/friocasino-api'
          - 'missaelcorm/friocasino-web'
      create_pull_request:
        description: 'Create a pull request to merge the changes'
        required: false
        default: false
        type: boolean
      environment:
        description: 'Environment to deploy the image'
        required: false
        default: 'dev'
        type: choice
        options:
          - 'dev'

permissions:
  contents: read
  security-events: write
  issues: write
  attestations: write

jobs:
  set_vars:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.vars.outputs.short_sha }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set outputs
      id: vars
      run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Check outputs
      run: echo ${{ steps.vars.outputs.short_sha }}

  build_and_push:
    runs-on: ubuntu-latest
    needs: [set_vars]
    env: 
      DOCKER_IMAGE: ${{ github.event.inputs.docker_image }}
      DOCKER_TAG: ${{ needs.set_vars.outputs.short_sha }}
    outputs:
      SERVICE: ${{ steps.set_docker_context.outputs.SERVICE }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set Docker Context
      id: set_docker_context
      run: |
        if [ "${{ env.DOCKER_IMAGE }}" == "missaelcorm/friocasino-api" ]; then
          echo "DOCKER_LOCAL_CONTEXT=backend" >> $GITHUB_ENV
          echo "SERVICE=backend" >> $GITHUB_OUTPUT
        elif [ "${{ env.DOCKER_IMAGE }}" == "missaelcorm/friocasino-web" ]; then
          echo "DOCKER_LOCAL_CONTEXT=frontend" >> $GITHUB_ENV
          echo "SERVICE=frontend" >> $GITHUB_OUTPUT
        fi

    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.3.0
      with:
        context: ./${{ env.DOCKER_LOCAL_CONTEXT }}
        file: ./${{ env.DOCKER_LOCAL_CONTEXT }}/Dockerfile
        push: true
        tags: "${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}"

    - name: Send notification to Slack
      uses: ./.github/actions/slack-notify
      if: always()
      with:
        job_name: 'Build and Push Docker Image'
        job_status: ${{ job.status }}
        github_workflow: ${{ github.workflow}}
        repo_name: ${{ github.repository }}
        branch_name: ${{ github.ref }}
        commit_sha: ${{ github.sha }}
        slack_channel: '#notifications'
        slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

  trivy_security_scan:
    runs-on: ubuntu-latest
    needs: [set_vars, build_and_push]
    env: 
      DOCKER_IMAGE: ${{ github.event.inputs.docker_image }}
      DOCKER_TAG: ${{ needs.set_vars.outputs.short_sha }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner
      id: trivy
      uses: aquasecurity/trivy-action@master
      env:
        TRIVY_DB_REPOSITORY: 'public.ecr.aws/aquasecurity/trivy-db:2'
      with:
        image-ref: '${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}'
        format: 'json'
        output: 'trivy-results.json'
        exit-code: '1'
        ignore-unfixed: false
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH,MEDIUM'
      continue-on-error: true

    - name: Upload Trivy scan results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: security-trivy-friocasino-json-${{ github.sha }}
        path: trivy-results.json

    - name: Send notification to Slack
      uses: ./.github/actions/slack-notify
      if: always()
      with:
        job_name: 'Trivy Security Scan'
        job_status: ${{ steps.trivy.outcome }}
        github_workflow: ${{ github.workflow}}
        repo_name: ${{ github.repository }}
        branch_name: ${{ github.ref }}
        commit_sha: ${{ github.sha }}
        slack_channel: '#notifications'
        slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

  codeql_security_scan:
    runs-on: ubuntu-latest
    needs: [set_vars, build_and_push]
    env: 
      DOCKER_IMAGE: ${{ github.event.inputs.docker_image }}
      DOCKER_TAG: ${{ needs.set_vars.outputs.short_sha }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: 'javascript'

    - name: Perform CodeQL Analysis
      id: codeql
      uses: github/codeql-action/analyze@v3
      with:
        category: 'codeql-${{ github.event.inputs.docker_image }}'
        output: 'codeql-results.sarif' # Explicit output for CodeQL

    - name: Upload CodeQL Results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: security-codeql-friocasino-sarif-${{ github.sha }}
        path: codeql-results.sarif
        if-no-files-found: warn 
    
    - name: Send notification to Slack
      uses: ./.github/actions/slack-notify
      if: always()
      with:
        job_name: 'CodeQL Security Scan'
        job_status: ${{ steps.codeql.conclusion }}
        github_workflow: ${{ github.workflow}}
        repo_name: ${{ github.repository }}
        branch_name: ${{ github.ref }}
        commit_sha: ${{ github.sha }}
        slack_channel: '#notifications'
        slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy_pull_request:
    needs: [set_vars, build_and_push]
    uses: DavidHCM/casino/.github/workflows/create-docker-tag-pr.yml@develop/aws-infra
    if: ${{ github.event.inputs.create_pull_request == 'true' }}
    with:
      service: ${{ needs.build_and_push.outputs.SERVICE }}
      docker-image: ${{ github.event.inputs.docker_image }}
      docker-tag: ${{ needs.set_vars.outputs.short_sha }}
      github-repository: ${{ github.repository }}
      github-actor: ${{ github.actor }}
      environment: ${{ github.event.inputs.environment }}
      github-sha: ${{ github.sha }}
    secrets:
      GITHUB_TOKEN_INPUT: ${{ secrets.FRIOCASINO_AWS_PR_ACCESS_TOKEN }}