name: Terraform CI

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Working Directory'
        required: true
        type: string
    secrets:
      aws_access_key_id:
        description: 'AWS Access Key ID'
        required: true
      aws_secret_access_key:
        description: 'AWS Secret Access Key'
        required: true
      cloudflare_api_token:
        description: 'Cloudflare API Token'
        required: true
      stripe_secret_key:
        description: 'Stripe Secret Key'
        required: true
      SLACK_WEBHOOK_URL:
        description: 'Slack Webhook Url'
        required: true
    outputs:  
      tfplan-artifact-id:
        description: 'Terraform Plan Artifact ID'
        value: ${{ jobs.terraform-ci.outputs.tfplan-artifact-id }}
    
jobs:
  lambda-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Build Lambda Deployment Package
        run: |
          cd lambdas/payments
          npm ci
          npm run build

      - name: Upload Lambda Payments Artifact
        id: upload-lambda-zip
        uses: actions/upload-artifact@v4
        with:
          name: lambda-payments
          path: ./lambdas/payments/lambda-payments.zip

  terraform-ci:
    runs-on: ubuntu-latest
    needs: "lambda-ci"
    container: "missaelcorm/terratool:v0.10"
    outputs:
      tfplan-artifact-id: ${{ steps.upload.outputs.artifact-id }}
    env:
      TF_LOG: INFO
      AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
      TF_VAR_cloudflare_api_token: ${{ secrets.cloudflare_api_token }}
      TF_VAR_stripe_secret_key: ${{ secrets.stripe_secret_key }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lambda Payments Artifact
        uses: actions/download-artifact@master
        with:
          name: lambda-payments
          path: ./lambdas/payments

      - name: Terraform Init
        id: init
        working-directory: ${{ github.workspace }}/${{ inputs.working-directory }}
        run: |
          terraform init -input=false
          
      - name: Terraform Format
        id: fmt
        working-directory: ${{ github.workspace }}/${{ inputs.working-directory }}
        run: |
          terraform fmt -check=true -diff=true
        continue-on-error: true
      
      - name: Terraform Lint
        id: lint
        run: |
          tflint --init --recursive --config $(pwd)/infra/.tflint.hcl
          tflint --recursive --config $(pwd)/infra/.tflint.hcl 

      - name: Terraform Validate
        id: validate
        working-directory: ${{ github.workspace }}/${{ inputs.working-directory }}
        run: |
          terraform validate

      - name: Terraform Plan
        id: plan
        working-directory: ${{ github.workspace }}/${{ inputs.working-directory }}
        run: |
          terraform plan -input=false -compact-warnings -out=tfplan
        
      - name: Upload Terraform Plan Artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ${{ inputs.working-directory }}/tfplan

      - name: Send notification to Slack
        uses: ./.github/actions/slack-notify
        if: always()
        with:
          job_name: 'Terraform CI'
          job_status: ${{ job.status }}
          github_workflow: ${{ github.workflow }}
          repo_name: ${{ github.repository }}
          branch_name: ${{ github.ref }}
          commit_sha: ${{ github.sha }}
          slack_channel: '#notifications'
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
