name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      trigger_destroy:
        description: 'Trigger Destroy'
        required: false
        type: boolean
        default: false

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    container: "missaelcorm/terratool:v0.10"
    env:
      TF_LOG: INFO
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Terraform Init
        id: init
        working-directory: ${{ github.workspace }}/infra//environments/dev
        run: |
          terraform init -input=false

      - name: Terraform Plan Destroy
        id: plan
        working-directory: ${{ github.workspace }}/infra/environments/dev
        run: |
          terraform plan -destroy

      - name: Terraform Destroy
        id: destroy
        if: ${{ github.event.inputs.trigger_destroy == 'true' }}
        working-directory: ${{ github.workspace }}/infra/environments/dev
        run: |
          terraform destroy -auto-approve